// This file was generated by the Makefile

#ifndef MODELS_FILE_DEF
#define MODELS_FILE_DEF

#define MODEL_LEVEL "models/level.yuk2"
#define MODEL_AK_CAR_NO_ANIMATION "models/ak_car_no_animation.yuk2"
#define MODEL_NEP_AK "models/Nep_ak.yuk2"
#define MODEL_GROUND "models/ground.yuk2"
#define MODEL_LEVEL_HALO "models/level_halo.yuk2"
#define MODEL_AK "models/ak.yuk2"
#define MODEL_DICK "models/dick.yuk2"
#define MODEL_AK_CAR "models/ak_car.yuk2"
#define MODEL_REI "models/rei.yuk2"
#define MODEL_NEP "models/Nep.yuk2"
#define ANIMATION_AK_RELOAD "models/ak_Reload.anm"
#define ANIMATION_NEP_AK_ARMATUREACTION "models/Nep_ak_ArmatureAction.anm"
#define ANIMATION_DICK_ARMATUREACTION "models/dick_ArmatureAction.anm"
#define ANIMATION_REI_ARMATUREACTION "models/rei_ArmatureAction.anm"
#define ANIMATION_NEP_HEARTROUGH "models/Nep_HeartRough.anm"
#define ANIMATION_AK_CAR_ARMATUREACTION_001 "models/ak_car_ArmatureAction.001.anm"
#define ANIMATION_AK_CAR_DOOROPEN "models/ak_car_DoorOpen.anm"

#endif
