// This file was generated by the Makefile

#include <GL/glew.h>
#include "shader_files.h"
#include "shaders.h"

static Shader shaders[NUM_PROGRAMS];

void Shaders_CompileAll(void){
	Shader_CompileShader(&shaders[PROGRAM_shadow_mask], "shaders/shadow_mask.vs", "shaders/shadow_mask.fs");
	shaders[PROGRAM_shadow_mask].fUniforms[FUNIFORM_shadowsTexture] = glGetUniformLocation(shaders[PROGRAM_shadow_mask].program, "shadowsTexture");
	shaders[PROGRAM_shadow_mask].fUniforms[FUNIFORM_depthTexture] = glGetUniformLocation(shaders[PROGRAM_shadow_mask].program, "depthTexture");
	shaders[PROGRAM_shadow_mask].fUniforms[FUNIFORM_invProjView] = glGetUniformLocation(shaders[PROGRAM_shadow_mask].program, "invProjView");
	shaders[PROGRAM_shadow_mask].fUniforms[FUNIFORM_darknesses] = glGetUniformLocation(shaders[PROGRAM_shadow_mask].program, "darknesses");
	shaders[PROGRAM_shadow_mask].fUniforms[FUNIFORM_lightMatrices] = glGetUniformLocation(shaders[PROGRAM_shadow_mask].program, "lightMatrices");
	shaders[PROGRAM_shadow_mask].fUniforms[FUNIFORM_nSources] = glGetUniformLocation(shaders[PROGRAM_shadow_mask].program, "nSources");
	Shader_CompileShader(&shaders[PROGRAM_bloom_pass_two], "shaders/bloom_pass_two.vs", "shaders/bloom_pass_two.fs");
	shaders[PROGRAM_bloom_pass_two].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_bloom_pass_two].program, "tex");
	shaders[PROGRAM_bloom_pass_two].fUniforms[FUNIFORM_texelSize] = glGetUniformLocation(shaders[PROGRAM_bloom_pass_two].program, "texelSize");
	shaders[PROGRAM_bloom_pass_two].fUniforms[FUNIFORM_weights] = glGetUniformLocation(shaders[PROGRAM_bloom_pass_two].program, "weights");
	Shader_CompileShader(&shaders[PROGRAM_light_prepass], "shaders/light_prepass.vs", "shaders/light_prepass.fs");
	shaders[PROGRAM_light_prepass].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "projView");
	shaders[PROGRAM_light_prepass].vUniforms[VUNIFORM_center] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "center");
	shaders[PROGRAM_light_prepass].vUniforms[VUNIFORM_radius] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "radius");
	shaders[PROGRAM_light_prepass].fUniforms[FUNIFORM_depthTexture] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "depthTexture");
	shaders[PROGRAM_light_prepass].fUniforms[FUNIFORM_normalTexture] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "normalTexture");
	shaders[PROGRAM_light_prepass].fUniforms[FUNIFORM_invProj] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "invProj");
	shaders[PROGRAM_light_prepass].fUniforms[FUNIFORM_lightCenter] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "lightCenter");
	shaders[PROGRAM_light_prepass].fUniforms[FUNIFORM_color] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "color");
	shaders[PROGRAM_light_prepass].fUniforms[FUNIFORM_ambient] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "ambient");
	shaders[PROGRAM_light_prepass].fUniforms[FUNIFORM_lightAmbient] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "lightAmbient");
	shaders[PROGRAM_light_prepass].fUniforms[FUNIFORM_lightLinear] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "lightLinear");
	shaders[PROGRAM_light_prepass].fUniforms[FUNIFORM_lightQuadratic] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "lightQuadratic");
	shaders[PROGRAM_light_prepass].fUniforms[FUNIFORM_lightConstant] = glGetUniformLocation(shaders[PROGRAM_light_prepass].program, "lightConstant");
	Shader_CompileShader(&shaders[PROGRAM_bright_pass_filter], "shaders/bright_pass_filter.vs", "shaders/bright_pass_filter.fs");
	shaders[PROGRAM_bright_pass_filter].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_bright_pass_filter].program, "tex");
	shaders[PROGRAM_bright_pass_filter].fUniforms[FUNIFORM_threshold] = glGetUniformLocation(shaders[PROGRAM_bright_pass_filter].program, "threshold");
	Shader_CompileShader(&shaders[PROGRAM_ssao_blur_h], "shaders/ssao_blur_h.vs", "shaders/ssao_blur_h.fs");
	shaders[PROGRAM_ssao_blur_h].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_ssao_blur_h].program, "tex");
	shaders[PROGRAM_ssao_blur_h].fUniforms[FUNIFORM_texelSize] = glGetUniformLocation(shaders[PROGRAM_ssao_blur_h].program, "texelSize");
	shaders[PROGRAM_ssao_blur_h].fUniforms[FUNIFORM_blurSize] = glGetUniformLocation(shaders[PROGRAM_ssao_blur_h].program, "blurSize");
	Shader_CompileShader(&shaders[PROGRAM_fxaa], "shaders/fxaa.vs", "shaders/fxaa.fs");
	shaders[PROGRAM_fxaa].vUniforms[VUNIFORM_texelSize] = glGetUniformLocation(shaders[PROGRAM_fxaa].program, "texelSize");
	shaders[PROGRAM_fxaa].vUniforms[VUNIFORM_FXAA] = glGetUniformLocation(shaders[PROGRAM_fxaa].program, "FXAA");
	shaders[PROGRAM_fxaa].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_fxaa].program, "tex");
	shaders[PROGRAM_fxaa].fUniforms[FUNIFORM_depthTexture] = glGetUniformLocation(shaders[PROGRAM_fxaa].program, "depthTexture");
	shaders[PROGRAM_fxaa].fUniforms[FUNIFORM_texelSize] = glGetUniformLocation(shaders[PROGRAM_fxaa].program, "texelSize");
	Shader_CompileShader(&shaders[PROGRAM_2d], "shaders/2d.vs", "shaders/2d.fs");
	shaders[PROGRAM_2d].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_2d].program, "projView");
	shaders[PROGRAM_2d].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_2d].program, "tex");
	shaders[PROGRAM_2d].fUniforms[FUNIFORM_uniformColor] = glGetUniformLocation(shaders[PROGRAM_2d].program, "uniformColor");
	Shader_CompileShader(&shaders[PROGRAM_bloom_pass_one], "shaders/bloom_pass_one.vs", "shaders/bloom_pass_one.fs");
	shaders[PROGRAM_bloom_pass_one].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_bloom_pass_one].program, "tex");
	shaders[PROGRAM_bloom_pass_one].fUniforms[FUNIFORM_texelSize] = glGetUniformLocation(shaders[PROGRAM_bloom_pass_one].program, "texelSize");
	shaders[PROGRAM_bloom_pass_one].fUniforms[FUNIFORM_weights] = glGetUniformLocation(shaders[PROGRAM_bloom_pass_one].program, "weights");
	Shader_CompileShader(&shaders[PROGRAM_textureless_skinned], "shaders/textureless_skinned.vs", "shaders/textureless_skinned.fs");
	shaders[PROGRAM_textureless_skinned].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "projView");
	shaders[PROGRAM_textureless_skinned].vUniforms[VUNIFORM_model] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "model");
	shaders[PROGRAM_textureless_skinned].vUniforms[VUNIFORM_bones] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "bones");
	shaders[PROGRAM_textureless_skinned].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "tex");
	shaders[PROGRAM_textureless_skinned].fUniforms[FUNIFORM_ssao] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "ssao");
	shaders[PROGRAM_textureless_skinned].fUniforms[FUNIFORM_shadowMask] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "shadowMask");
	shaders[PROGRAM_textureless_skinned].fUniforms[FUNIFORM_lightSpecular] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "lightSpecular");
	shaders[PROGRAM_textureless_skinned].fUniforms[FUNIFORM_lightDiffuse] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "lightDiffuse");
	shaders[PROGRAM_textureless_skinned].fUniforms[FUNIFORM_ambient] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "ambient");
	shaders[PROGRAM_textureless_skinned].fUniforms[FUNIFORM_diffuse] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "diffuse");
	shaders[PROGRAM_textureless_skinned].fUniforms[FUNIFORM_specular] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "specular");
	shaders[PROGRAM_textureless_skinned].fUniforms[FUNIFORM_gamma] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "gamma");
	shaders[PROGRAM_textureless_skinned].fUniforms[FUNIFORM_mode] = glGetUniformLocation(shaders[PROGRAM_textureless_skinned].program, "mode");
	Shader_CompileShader(&shaders[PROGRAM_skinned_passthrough], "shaders/skinned_passthrough.vs", "shaders/skinned_passthrough.fs");
	shaders[PROGRAM_skinned_passthrough].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough].program, "projView");
	shaders[PROGRAM_skinned_passthrough].vUniforms[VUNIFORM_modelInvTranspose] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough].program, "modelInvTranspose");
	shaders[PROGRAM_skinned_passthrough].vUniforms[VUNIFORM_view] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough].program, "view");
	shaders[PROGRAM_skinned_passthrough].vUniforms[VUNIFORM_model] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough].program, "model");
	shaders[PROGRAM_skinned_passthrough].vUniforms[VUNIFORM_bones] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough].program, "bones");
	shaders[PROGRAM_skinned_passthrough].fUniforms[FUNIFORM_specularHardness] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough].program, "specularHardness");
	Shader_CompileShader(&shaders[PROGRAM_standard_3d_passthrough], "shaders/standard_3d_passthrough.vs", "shaders/standard_3d_passthrough.fs");
	shaders[PROGRAM_standard_3d_passthrough].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough].program, "projView");
	shaders[PROGRAM_standard_3d_passthrough].vUniforms[VUNIFORM_model] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough].program, "model");
	shaders[PROGRAM_standard_3d_passthrough].vUniforms[VUNIFORM_view] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough].program, "view");
	shaders[PROGRAM_standard_3d_passthrough].vUniforms[VUNIFORM_modelInvTranspose] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough].program, "modelInvTranspose");
	shaders[PROGRAM_standard_3d_passthrough].fUniforms[FUNIFORM_proj] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough].program, "proj");
	shaders[PROGRAM_standard_3d_passthrough].fUniforms[FUNIFORM_invProjWW] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough].program, "invProjWW");
	shaders[PROGRAM_standard_3d_passthrough].fUniforms[FUNIFORM_specularHardness] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough].program, "specularHardness");
	Shader_CompileShader(&shaders[PROGRAM_ssao_blur_v], "shaders/ssao_blur_v.vs", "shaders/ssao_blur_v.fs");
	shaders[PROGRAM_ssao_blur_v].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_ssao_blur_v].program, "tex");
	shaders[PROGRAM_ssao_blur_v].fUniforms[FUNIFORM_texelSize] = glGetUniformLocation(shaders[PROGRAM_ssao_blur_v].program, "texelSize");
	shaders[PROGRAM_ssao_blur_v].fUniforms[FUNIFORM_blurSize] = glGetUniformLocation(shaders[PROGRAM_ssao_blur_v].program, "blurSize");
	Shader_CompileShader(&shaders[PROGRAM_standard_3d], "shaders/standard_3d.vs", "shaders/standard_3d.fs");
	shaders[PROGRAM_standard_3d].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "projView");
	shaders[PROGRAM_standard_3d].vUniforms[VUNIFORM_view] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "view");
	shaders[PROGRAM_standard_3d].vUniforms[VUNIFORM_model] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "model");
	shaders[PROGRAM_standard_3d].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "tex");
	shaders[PROGRAM_standard_3d].fUniforms[FUNIFORM_ssao] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "ssao");
	shaders[PROGRAM_standard_3d].fUniforms[FUNIFORM_shadowMask] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "shadowMask");
	shaders[PROGRAM_standard_3d].fUniforms[FUNIFORM_lightSpecular] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "lightSpecular");
	shaders[PROGRAM_standard_3d].fUniforms[FUNIFORM_lightDiffuse] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "lightDiffuse");
	shaders[PROGRAM_standard_3d].fUniforms[FUNIFORM_ambient] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "ambient");
	shaders[PROGRAM_standard_3d].fUniforms[FUNIFORM_diffuse] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "diffuse");
	shaders[PROGRAM_standard_3d].fUniforms[FUNIFORM_specular] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "specular");
	shaders[PROGRAM_standard_3d].fUniforms[FUNIFORM_gamma] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "gamma");
	shaders[PROGRAM_standard_3d].fUniforms[FUNIFORM_mode] = glGetUniformLocation(shaders[PROGRAM_standard_3d].program, "mode");
	Shader_CompileShader(&shaders[PROGRAM_textureless_2d], "shaders/textureless_2d.vs", "shaders/textureless_2d.fs");
	shaders[PROGRAM_textureless_2d].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_textureless_2d].program, "projView");
	shaders[PROGRAM_textureless_2d].fUniforms[FUNIFORM_uniformColor] = glGetUniformLocation(shaders[PROGRAM_textureless_2d].program, "uniformColor");
	Shader_CompileShader(&shaders[PROGRAM_ssao], "shaders/ssao.vs", "shaders/ssao.fs");
	shaders[PROGRAM_ssao].vUniforms[VUNIFORM_aspect] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "aspect");
	shaders[PROGRAM_ssao].vUniforms[VUNIFORM_tanHalfFov] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "tanHalfFov");
	shaders[PROGRAM_ssao].fUniforms[FUNIFORM_radius] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "radius");
	shaders[PROGRAM_ssao].fUniforms[FUNIFORM_depthTexture] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "depthTexture");
	shaders[PROGRAM_ssao].fUniforms[FUNIFORM_normalTexture] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "normalTexture");
	shaders[PROGRAM_ssao].fUniforms[FUNIFORM_randomTexture] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "randomTexture");
	shaders[PROGRAM_ssao].fUniforms[FUNIFORM_noiseScale] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "noiseScale");
	shaders[PROGRAM_ssao].fUniforms[FUNIFORM_proj] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "proj");
	shaders[PROGRAM_ssao].fUniforms[FUNIFORM_invProjWW] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "invProjWW");
	shaders[PROGRAM_ssao].fUniforms[FUNIFORM_texelSize] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "texelSize");
	shaders[PROGRAM_ssao].fUniforms[FUNIFORM_kernel] = glGetUniformLocation(shaders[PROGRAM_ssao].program, "kernel");
	Shader_CompileShader(&shaders[PROGRAM_textureless_3d], "shaders/textureless_3d.vs", "shaders/textureless_3d.fs");
	shaders[PROGRAM_textureless_3d].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "projView");
	shaders[PROGRAM_textureless_3d].vUniforms[VUNIFORM_view] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "view");
	shaders[PROGRAM_textureless_3d].vUniforms[VUNIFORM_model] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "model");
	shaders[PROGRAM_textureless_3d].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "tex");
	shaders[PROGRAM_textureless_3d].fUniforms[FUNIFORM_ssao] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "ssao");
	shaders[PROGRAM_textureless_3d].fUniforms[FUNIFORM_shadowMask] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "shadowMask");
	shaders[PROGRAM_textureless_3d].fUniforms[FUNIFORM_lightSpecular] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "lightSpecular");
	shaders[PROGRAM_textureless_3d].fUniforms[FUNIFORM_lightDiffuse] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "lightDiffuse");
	shaders[PROGRAM_textureless_3d].fUniforms[FUNIFORM_ambient] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "ambient");
	shaders[PROGRAM_textureless_3d].fUniforms[FUNIFORM_diffuse] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "diffuse");
	shaders[PROGRAM_textureless_3d].fUniforms[FUNIFORM_specular] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "specular");
	shaders[PROGRAM_textureless_3d].fUniforms[FUNIFORM_gamma] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "gamma");
	shaders[PROGRAM_textureless_3d].fUniforms[FUNIFORM_mode] = glGetUniformLocation(shaders[PROGRAM_textureless_3d].program, "mode");
	Shader_CompileShader(&shaders[PROGRAM_tone_mapping_bloom], "shaders/tone_mapping_bloom.vs", "shaders/tone_mapping_bloom.fs");
	shaders[PROGRAM_tone_mapping_bloom].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_tone_mapping_bloom].program, "tex");
	shaders[PROGRAM_tone_mapping_bloom].fUniforms[FUNIFORM_bloomTexture] = glGetUniformLocation(shaders[PROGRAM_tone_mapping_bloom].program, "bloomTexture");
	Shader_CompileShader(&shaders[PROGRAM_skinned], "shaders/skinned.vs", "shaders/skinned.fs");
	shaders[PROGRAM_skinned].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "projView");
	shaders[PROGRAM_skinned].vUniforms[VUNIFORM_model] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "model");
	shaders[PROGRAM_skinned].vUniforms[VUNIFORM_bones] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "bones");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "tex");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_ssao] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "ssao");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_shadowMask] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "shadowMask");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_lightMask] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "lightMask");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_lightSpecular] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "lightSpecular");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_lightDiffuse] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "lightDiffuse");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_ambient] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "ambient");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_diffuse] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "diffuse");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_specular] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "specular");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_gamma] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "gamma");
	shaders[PROGRAM_skinned].fUniforms[FUNIFORM_mode] = glGetUniformLocation(shaders[PROGRAM_skinned].program, "mode");
	Shader_CompileShader(&shaders[PROGRAM_skinned_passthrough_normalmap], "shaders/skinned_passthrough_normalmap.vs", "shaders/skinned_passthrough_normalmap.fs");
	shaders[PROGRAM_skinned_passthrough_normalmap].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough_normalmap].program, "projView");
	shaders[PROGRAM_skinned_passthrough_normalmap].vUniforms[VUNIFORM_view] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough_normalmap].program, "view");
	shaders[PROGRAM_skinned_passthrough_normalmap].vUniforms[VUNIFORM_model] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough_normalmap].program, "model");
	shaders[PROGRAM_skinned_passthrough_normalmap].vUniforms[VUNIFORM_modelInvTranspose] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough_normalmap].program, "modelInvTranspose");
	shaders[PROGRAM_skinned_passthrough_normalmap].vUniforms[VUNIFORM_bones] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough_normalmap].program, "bones");
	shaders[PROGRAM_skinned_passthrough_normalmap].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough_normalmap].program, "tex");
	shaders[PROGRAM_skinned_passthrough_normalmap].fUniforms[FUNIFORM_specularHardness] = glGetUniformLocation(shaders[PROGRAM_skinned_passthrough_normalmap].program, "specularHardness");
	Shader_CompileShader(&shaders[PROGRAM_standard_3d_passthrough_normalmap], "shaders/standard_3d_passthrough_normalmap.vs", "shaders/standard_3d_passthrough_normalmap.fs");
	shaders[PROGRAM_standard_3d_passthrough_normalmap].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough_normalmap].program, "projView");
	shaders[PROGRAM_standard_3d_passthrough_normalmap].vUniforms[VUNIFORM_model] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough_normalmap].program, "model");
	shaders[PROGRAM_standard_3d_passthrough_normalmap].vUniforms[VUNIFORM_view] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough_normalmap].program, "view");
	shaders[PROGRAM_standard_3d_passthrough_normalmap].vUniforms[VUNIFORM_modelViewInvTranspose] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough_normalmap].program, "modelViewInvTranspose");
	shaders[PROGRAM_standard_3d_passthrough_normalmap].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough_normalmap].program, "tex");
	shaders[PROGRAM_standard_3d_passthrough_normalmap].fUniforms[FUNIFORM_specularHardness] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough_normalmap].program, "specularHardness");
	shaders[PROGRAM_standard_3d_passthrough_normalmap].fUniforms[FUNIFORM_normalFactor] = glGetUniformLocation(shaders[PROGRAM_standard_3d_passthrough_normalmap].program, "normalFactor");
	Shader_CompileShader(&shaders[PROGRAM_particles], "shaders/particles.vs", "shaders/particles.fs");
	shaders[PROGRAM_particles].vUniforms[VUNIFORM_projView] = glGetUniformLocation(shaders[PROGRAM_particles].program, "projView");
	shaders[PROGRAM_particles].vUniforms[VUNIFORM_model] = glGetUniformLocation(shaders[PROGRAM_particles].program, "model");
	shaders[PROGRAM_particles].vUniforms[VUNIFORM_camRight] = glGetUniformLocation(shaders[PROGRAM_particles].program, "camRight");
	shaders[PROGRAM_particles].vUniforms[VUNIFORM_camUp] = glGetUniformLocation(shaders[PROGRAM_particles].program, "camUp");
	shaders[PROGRAM_particles].fUniforms[FUNIFORM_proj] = glGetUniformLocation(shaders[PROGRAM_particles].program, "proj");
	shaders[PROGRAM_particles].fUniforms[FUNIFORM_softness] = glGetUniformLocation(shaders[PROGRAM_particles].program, "softness");
	shaders[PROGRAM_particles].fUniforms[FUNIFORM_tex] = glGetUniformLocation(shaders[PROGRAM_particles].program, "tex");
	shaders[PROGRAM_particles].fUniforms[FUNIFORM_depthTexture] = glGetUniformLocation(shaders[PROGRAM_particles].program, "depthTexture");
}

void Shaders_DestroyAll(void){
	Shader_DestroyShader(&shaders[PROGRAM_shadow_mask]);
	Shader_DestroyShader(&shaders[PROGRAM_bloom_pass_two]);
	Shader_DestroyShader(&shaders[PROGRAM_light_prepass]);
	Shader_DestroyShader(&shaders[PROGRAM_bright_pass_filter]);
	Shader_DestroyShader(&shaders[PROGRAM_ssao_blur_h]);
	Shader_DestroyShader(&shaders[PROGRAM_fxaa]);
	Shader_DestroyShader(&shaders[PROGRAM_2d]);
	Shader_DestroyShader(&shaders[PROGRAM_bloom_pass_one]);
	Shader_DestroyShader(&shaders[PROGRAM_textureless_skinned]);
	Shader_DestroyShader(&shaders[PROGRAM_skinned_passthrough]);
	Shader_DestroyShader(&shaders[PROGRAM_standard_3d_passthrough]);
	Shader_DestroyShader(&shaders[PROGRAM_ssao_blur_v]);
	Shader_DestroyShader(&shaders[PROGRAM_standard_3d]);
	Shader_DestroyShader(&shaders[PROGRAM_textureless_2d]);
	Shader_DestroyShader(&shaders[PROGRAM_ssao]);
	Shader_DestroyShader(&shaders[PROGRAM_textureless_3d]);
	Shader_DestroyShader(&shaders[PROGRAM_tone_mapping_bloom]);
	Shader_DestroyShader(&shaders[PROGRAM_skinned]);
	Shader_DestroyShader(&shaders[PROGRAM_skinned_passthrough_normalmap]);
	Shader_DestroyShader(&shaders[PROGRAM_standard_3d_passthrough_normalmap]);
	Shader_DestroyShader(&shaders[PROGRAM_particles]);
}

int Shaders_GetVUniformLoc(int program, int uniform){
	return shaders[program].vUniforms[uniform];
}

int Shaders_GetFUniformLoc(int program, int uniform){
	return shaders[program].fUniforms[uniform];
}

int Shaders_GetProgram(int program){
	return shaders[program].program;
}
